config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from user.views import signup,UserLoginView,KakaoSignInView,KakaoLoginCallback
import allauth

urlpatterns = [
    path('admin/', admin.site.urls),
    path('memo/', include('memo.urls')),
    path('',UserLoginView.as_view(), name="login"),
    path('signup/',signup,name="signup"),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('accounts/',include('allauth.urls')),
    
    path('kakao/',KakaoSignInView,name='kakaosignin'),
    path('kakao/login/callback',KakaoLoginCallback, name='kakaologincallback'),
]

memo/urls.py
from django.urls import path
from . import views

app_name = 'memo'

urlpatterns =[
    path("",views.MemoHomeListUpdateView,name="homelist"),
    path("list/",views.MemoListView,name="list"),
    path("delete/",views.MemoDeleteView,name="delete"),
    path("create/",views.MemoCreateView,name="create"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block title %}
    <!--타이틀-->
    {% endblock title %}
</head>

<body>
    <header class="flex-header-container">
        <div class="flex-container-list">
            <button class="flex-item" onclick="location.href='{% url "memo:homelist"%}'"></button>
            <button class="flex-item" onclick="location.href='{% url "memo:list"%}'"></button>
        </div>
        <div class="flex-container-1">
            <button class="flex-item"></button>
            <button class="flex-item"></button>
            {% comment %} 삭제버튼 {% endcomment %}
            <button class="flex-item" type="submit" form="delete"></button>
            {% comment %} 수정버튼 {% endcomment %}
            <button class="flex-item" type="submit" form="memosave"></button>
        </div>
        <div class="flex-container-2">
            <button class="flex-item"></button>
            <button class="flex-item"></button>
            <button class="flex-item"></button>
            <button class="flex-item"></button>
        </div>
        <div class="flex-container-search">
            <button class="flex-item"></button>
            {% comment %} 생성 버튼 {% endcomment %}
            <button class="flex-item" onclick="location.href='/memo/create'"></button>
            {% comment %} 로그아웃버튼 {% endcomment %}
            <button class="flex-item" onclick="location.href='/logout'"></button>
            <input type="search" name="search" value="검색" id="">

        </div>
        <div>
            {% if user.nickname %}
            {{user.nickname}}님이 사용중
            {%else%}
            {{user.username}}님이 사용중
            {% endif %}
        </div>
    </header>
    {% block content %}
    <!--본문-->
    {% endblock content %}
    <script>
        // 900px 3-2버튼 -> 845px 4-3버튼 -> 800px 4-1버튼 -> 745px 3-4버튼 -> 700px 3-3버튼 -> 660px 검색창 -> 480 미니멀
        // 삭제 코드
        // var re = document.getElementsByClassName("flex-container-list")[0];
        // var move = document.getElementsByClassName('flex-item')[0];
        // move.parentNode.removeChild(move);

        function printName() {
            var memoTitle = getElementById("id_contents").value;
            console.log(memoTitle);
        };
    </script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}
<title>HOME</title>
{% endblock title %}

{% block content %}
<section class="flex-container-section-wrap">
    <nav class="flex-container-nav">
        <div class="flex-container-nav-list">
            <div class="menu-block-1">
                {%for memo in memolist%}
                <div id="memo-title" value="새로운 메모"></div>
                <div id="memo-contents"> {{memo.memoNUM.memodate | date:'A H:i' }}</div>
                {% endfor %}
            </div>
            <div class="menu-block-2">
                <!--여기서 새로 생긴다. 이유는 for문에서 할당하지 않았으니까-->
                {%for memo in memolist%}
                <!--{{memo.memoNUM.memodate}}<br>-->
                <a href="?pk={{memo.memoNUM.pk}}">

                    {{memo.memoNUM.title | truncatechars:20}}
                    <h1 style="font-weight: bold;">{{memo.memoNUM.contents | truncatechars:20}}</h1>
                    {{memo.memoNUM.memodate | date:'A H:i' }}

                </a>
                {% endfor %}
            </div>
        </div>
    </nav>
    <article class="flex-container-section-wrap">
        <div class="flex-container-section">
            <div>
                
                {% if pk_memoupdate  %}
                    수정일 : {{pk_memoupdate}}
                {% elif pk_memodate %}
                    저장일 : {{pk_memodate}}
                {% else %}
                    현재 : {{now}}
                {% endif %}
                
            </div>

            {% comment %} 내용출력 {% endcomment %}

            <form method="post" id="memosave">
                {% csrf_token %}
                {{form.contents}}
                {% comment %} <input type="submit" value="메모저장"> {% endcomment %}
                <input type="hidden" name="pk" value="{{pk}}">
            </form>

            {% comment %} 메모저장폼 {% endcomment %}
            <form method="post" id="delete" action="{%url 'memo:delete'%}">
                {% csrf_token %}
                <input type="hidden" name="pk" value="{{pk}}">
            </form>

        </div>
    </article>
</section>
{% endblock content %}

templates/list.html
{% extends 'base.html' %}

{% block title %}
<title>List</title>
{% endblock title %}

{% block content %}
<nav class="flex-container-list-page">
    <div>

        {%for memo in memolist%}

        <h3>제목 : {{memo.memoNUM.title}}</h3>
        <p>내용 : {{memo.memoNUM.contents}}</p>
        유저 : {{memo.userNUM}}<br>
        작성일시 : {{memo.memoNUM.memodate}}<br>
        {% comment %} 작성번호 : {{memo.memoNUM.pk}}<br> {% endcomment %}


        {% endfor %}
    </div>
</nav>
{% endblock content %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Login</title>
</head>

<body class="login-body">
    {% comment %} /* Change autocomplete styles in WebKit */ {% endcomment %}
    <div class="login-container">
        <form method="POST" action="" class="frame-form">
            {% csrf_token %}
            <fieldset class="login-fieldset">
                <form method="POST" class="login-form">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="login-area">
                        <div style="color: white; font-family: Geogia;">{{field.label}}</div><div class="login-input-area">{{field}}</div>
                    </div>
                    {% endfor %}
                    <div class="button-container">
                        <button type="submit" value="login">Login</button>
                        <button type="button" onclick="location.href='{% url "signup" %}'" value="Sign up">Sign up</button>
                    </div>
                </form>
                <div class="allauto-container">
                    {% load socialaccount %}
                    {% providers_media_js %}
                    <a href="{% provider_login_url "google" %}">구글로 계속하기</a>
                    <a href="{% provider_login_url "naver" %}">네이버로 계속하기</a>
                    <a href="{%url 'kakaosignin' %}">카카오로 계속하기</a>
                </div>

            </fieldset>
        </form>
    </div>
</body>

</html>

templates/signup.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SignUP</title>
</head>

<body>
    <form method="post" action="">
        {% csrf_token %}
        <fieldset>
            <legend>회원가입</legend>

                <form method="post">
                {% csrf_token %}
                
                        {{form.as_p}} 
                </form>

            <input type="submit" value="확인">
            <input type="submit" value="취소">
        </fieldset>
    </form>
</body>

</html>